### ISSUE TITLE
Update from 1.0.3 -> 1.0.4 breaks build

### ISSUE THREAD

**Issue by elderfd** [fossamagna/gas-webpack-plugin#411]
Our project was building fine on 1.0.3 but after upgrading to 1.0.4 we get an error,

```
ERROR in main.js from es3ify
TypeError: asset.map is not a function
    at <redacted>/node_modules/es3ify-webpack-plugin/index.js:65:31
    at Array.forEach (<anonymous>)
    at <redacted>/node_modules/es3ify-webpack-plugin/index.js:55:10
    at _next0 (eval at create (<redacted>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (<redacted>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at <redacted>/node_modules/gas-webpack-plugin/index.js:33:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<redacted>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at AsyncSeriesHook.lazyCompileHook (<redacted>/node_modules/tapable/lib/Hook.js:154:20)
    at <redacted>/node_modules/webpack/lib/Compilation.js:1409:36
    at eval (eval at create (<redacted>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at <redacted>/node_modules/copy-webpack-plugin/dist/index.js:101:9
```

Downgrading to 1.0.3 fixed the issue so not a major problem for us.

**Comment by fossamagna** [comment]
Thank you @elderfd 
Can I see your webpack configuration file (ex: webpack.config.js).

**Comment by elderfd** [comment]
```
const path = require('path');
const GasPlugin = require('gas-webpack-plugin');
const es3ifyPlugin = require('es3ify-webpack-plugin');

module.exports = function (env, argv) {
    let plugins = [
        new GasPlugin(),
        new es3ifyPlugin(),
    ];

    let cfg = {
        devtool: 'none',
        entry: `./src/main.ts`,
        output: {
            filename: 'main.js',
            path: `${__dirname}/dist`,
        },
        module: {
            rules: [
                {
                    test: /(\.ts)$/,
                    loader: 'ts-loader',
                },
            ],
        },
        resolve: {
            extensions: ['.ts'],
            alias: aliases,
        },
        plugins: plugins,
        optimization: {
            minimize: false,
        },
    };

    return cfg;
};
```

**Comment by fossamagna** [comment]
@elderfd A new version is now available. Try it out.
https://www.npmjs.com/package/gas-webpack-plugin/v/1.0.5
